### PR TITLE
Allow setting the host parameter

### PR DESCRIPTION
**Pull request by jacobkiers**
Hi, thanks a lot for this project!

This contribution adds the ability to set the host parameters, as requested in #1. I had the exact same issue, and decided to fix it.

Maybe obvious, but this fix is contributed under the same license terms as this project.

If this is not something you'd like to include, feel free to close it.

### CODE REVIEW

**Comment by sobjornstad** [comment]
Great idea. Would you mind also allowing a default value to be set in the config file like the port? We could set it to `localhost` by default and include a comment.

https://github.com/sobjornstad/tzk/blob/35ca2b896e90e1570b155e6e18c801ae6ee3ce04/tzk/default_config.py#L33

**Comment by jacobkiers** [comment]
Sure! I'm not too familiar with Python though, these two PRs came about with quite some effort :)

Is it just a question of adding a line like this:

```python
# Documentation...
host = 'localhost'
```

Or do I need to do more than that to make it work?

**Comment by sobjornstad** [comment]
The `__getattr__()` magic method of the `ConfigurationManager` ([here](https://github.com/sobjornstad/tzk/blob/master/tzk/config.py#L26)) will make `host` available as an attribute of `cm()` if it's in the config file. But then you need to use that property as the default value for the command-line option, so it will get picked up if no value is specified on the command line. Look at how the `--port` option does this here:

https://github.com/sobjornstad/tzk/blob/35ca2b896e90e1570b155e6e18c801ae6ee3ce04/tzk/__main__.py#L90

It appears that in what you have right now, you already copied that line without understanding what it did (it's working fine because the `__getattr__()` is defined to return `None` if the property doesn't exist, so it ends up falling back to `localhost` in all cases). So I think all you need to do is change the name of the attribute you're looking for on `cm()` to `host` and add the `host` property to the default config.

**Comment by jacobkiers** [comment]
I think this is done now.

> (..) It appears that in what you have right now, you already copied that line without understanding what it did (...)

Yes, that is what I tend to do with unfamiliar code. That gives the greatest chance of getting something to work quickly.

And it _did_ work, indeed, but apparently I forgot a step...

Thanks for the guidance!

**Comment by sobjornstad** [comment]
Looks good, thanks!

**Pull request merged**
